sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['create', 'index']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
    type: sylius.resource
