sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['index', 'update']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
        redirect: update
    type: sylius.resource


sylius_rbac_administration_role_new:
    path: /administration-roles/new
    methods: [GET, POST]
    defaults:
        _controller: sylius_rbac.controller.administration_role:createAction
        _sylius:
            template: "@SyliusRbacPlugin/AdministrationRole/create.html.twig"
