sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['index']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
        redirect: update
    type: sylius.resource


sylius_rbac_administration_role_new:
    path: /administration-roles/new
    methods: [GET]
    defaults:
        _controller: Sylius\RbacPlugin\Action\CreateAdministrationRoleCreatorViewAction

sylius_rbac_administration_role_create:
    path: /administration-roles/create
    defaults:
        _controller: Sylius\RbacPlugin\Action\CreateAdministrationRoleAction

sylius_rbac_administration_role_edit:
    path: /administration-roles/{id}/edit
    defaults:
        _controller: Sylius\RbacPlugin\Action\UpdateAdministrationRoleViewAction

sylius_rbac_administration_role_update:
    path: /administration-roles/{id}/update
    defaults:
        _controller: Sylius\RbacPlugin\Action\UpdateAdministrationRoleAction
