sylius_rbac_administration_role:
    resource: |
        alias: sylius_rbac.administration_role
        only: ['index', 'update']
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: sylius_rbac_administration_role
        redirect: update
    type: sylius.resource


sylius_rbac_administration_role_new:
    path: /administration-roles/new
    methods: [GET]
    defaults:
        _controller: Sylius\RbacPlugin\Action\NewAdministrationRoleCreatorAction

sylius_rbac_administration_role_create:
    path: /administration-roles/create
    methods: [POST]
    defaults:
        _controller: Sylius\RbacPlugin\Action\CreateAdministrationRoleAction
