language: php

dist: trusty

sudo: false

php:
    - 7.2
    - 7.3

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"
    - mkdir -p tests/Application/web/media/image

install:
    - composer install --no-interaction --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    - (cd tests/Application && bin/console assets:install --env=test -vvv)
    - (cd tests/Application && bin/console cache:warmup --env=test -vvv)
    - (cd tests/Application && yarn build)

    # Configure display
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16
    - export DISPLAY=:99

script:
    - composer validate --strict
    - composer analyse

    - vendor/bin/phpspec run
    - vendor/bin/behat --strict -vvv --no-interaction || vendor/bin/behat --strict -vvv --no-interaction --rerun

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
